/**
 * The uploaded résumé filename must survive any board's storage.
 *
 * e-estekhdam refuses uploads with "خطا در زمان ذخیره فایل" and keeps every file
 * an application uploads — its API has no delete. The old name was built by
 * replacing each non-ASCII character with "_", so a Persian name became a run of
 * underscores: unreadable, and IDENTICAL for any two names of the same length.
 * Two ads at one company produced the same filename.
 */
import { describe, expect, it } from "vitest";

import { asciiFileStem, resumeFileName } from "@/lib/resume/resume-templates";

const PERSIAN_NAME = "امیرحسین نوری";
const PERSIAN_CO = "نور بیست مهوین";

describe("asciiFileStem", () => {
  it("transliterates Persian rather than erasing it", () => {
    const stem = asciiFileStem(PERSIAN_NAME);
    expect(stem).toMatch(/^[A-Za-z0-9._-]+$/);
    expect(stem).not.toMatch(/^_+$/);
    expect(stem.length).toBeGreaterThan(3);
  });

  it("keeps Latin input readable", () => {
    expect(asciiFileStem("Amir Hossein Nouri")).toBe("Amir_Hossein_Nouri");
  });

  it("strips path and quoting characters that break a multipart upload", () => {
    expect(asciiFileStem('a/b\\c:d*e?f"g<h>i|j')).not.toMatch(/[\\/:*?"<>|]/);
  });

  it("never returns leading or trailing separators", () => {
    expect(asciiFileStem("  __ hello __  ")).toBe("hello");
  });
});

describe("resumeFileName", () => {
  it("is always pure ASCII, whatever the profile language", () => {
    const name = resumeFileName(PERSIAN_NAME, PERSIAN_CO, { unique: "tvQ8" });
    expect(name).toMatch(/^[A-Za-z0-9._-]+\.pdf$/);
  });

  it("prefers the user's declared Latin name", () => {
    const name = resumeFileName(PERSIAN_NAME, "Acme", { latinName: "Amir Hossein Nouri" });
    expect(name).toContain("Amir_Hossein_Nouri");
  });

  it("distinguishes two ads at the same company", () => {
    // The exact case that could collide: same person, same employer, two jobs.
    const a = resumeFileName(PERSIAN_NAME, "آی تی پرداز", { unique: "tvQ8" });
    const b = resumeFileName(PERSIAN_NAME, "آی تی پرداز", { unique: "tk3P" });
    expect(a).not.toBe(b);
  });

  it("never degenerates to underscores, the old failure", () => {
    const name = resumeFileName(PERSIAN_NAME, PERSIAN_CO, { unique: "tvQ8" });
    expect(name).not.toMatch(/^_+\.pdf$/);
    expect(name.replace(/[_.]/g, "").length).toBeGreaterThan(5);
  });

  it("still produces something usable with no name at all", () => {
    expect(resumeFileName("", null)).toBe("Resume.pdf");
    expect(resumeFileName("۱۲۳", null)).toMatch(/\.pdf$/);
  });

  it("carries no sign of being generated by a tool", () => {
    const name = resumeFileName(PERSIAN_NAME, "Acme", { unique: "tvQ8" });
    expect(name.toLowerCase()).not.toContain("karjoo");
    expect(name.toLowerCase()).not.toContain("tailored");
  });
});
