/**
 * Sentry Edge Configuration — کارجو (karjoo).
 *
 * Edge runtime init (proxy.ts / edge functions). Single-tenant `karjoo`,
 * DSN/env from process.env. Mirrors Fabric-Commerce's edge config minus the
 * multi-brand logic.
 */

import * as Sentry from '@sentry/nextjs'

const SENTRY_DSN = process.env.NEXT_PUBLIC_SENTRY_DSN || process.env.SENTRY_DSN

Sentry.init({
  dsn: SENTRY_DSN,

  // Environment — production-pinned; SENTRY_ENVIRONMENT overrides at runtime.
  environment: process.env.SENTRY_ENVIRONMENT || 'production',

  // Lower sample rate for the (higher-volume) edge.
  tracesSampleRate: process.env.NODE_ENV === 'production' ? 0.05 : 1.0,

  enabled: !!SENTRY_DSN,

  // Release tag — keep in sync with server/client for release health.
  release: process.env.SENTRY_RELEASE || process.env.NEXT_PUBLIC_SENTRY_RELEASE,

  // Surface edge console.error/warn as searchable Sentry Logs.
  enableLogs: true,
  integrations: [Sentry.consoleLoggingIntegration({ levels: ['error', 'warn'] })],

  // Tag every event with the single tenant.
  initialScope: {
    tags: {
      tenant: 'karjoo',
    },
  },

  ignoreErrors: ['NEXT_REDIRECT', 'NEXT_NOT_FOUND', 'Rate limit exceeded'],

  beforeSend(event) {
    if (process.env.NODE_ENV === 'development') {
      return null
    }
    // Drop smoke/test probes so they never reach the prod issue list.
    if (isSmokeEvent(event)) {
      return null
    }
    return event
  },
})

/**
 * Detect smoke/test events generated by verification scripts (incl.
 * /api/internal/obs-smoke). Contains-match so a synthesised `"{type}: {value}"`
 * message still matches.
 */
function isSmokeEvent(event: {
  message?: string
  exception?: { values?: Array<{ value?: string }> }
}): boolean {
  const candidates: string[] = []
  if (event.message) candidates.push(event.message)
  const values = event.exception?.values
  if (Array.isArray(values)) {
    for (const v of values) {
      if (v?.value) candidates.push(v.value)
    }
  }
  return candidates.some(
    (m) =>
      m.includes('VERIFY-') ||
      m.includes('VERIFY_') ||
      m.includes('ENV-VERIFY-') ||
      m.includes('ALERT TEST') ||
      m.includes('obs-smoke') ||
      m.includes('karjoo-smoke-') ||
      m.includes('Sentry Resend SMTP Test')
  )
}
